<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.0.1 setup script
 * Date: Thu, 17 May 2018 16:53:28 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'sanshisuile87';

/* End of servers configuration */

$cfg['blowfish_secret'] = '_{0&e%l=o1NXe2ulZx)jnm1kiX~0Th';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
